name: Initial setup
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v2
        with:
          node-version: 18
    - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-
    - name: 'Install Dependencies'
        run: yarn --frozen-lockfile --ignore-scripts --prefer-offline