name: Composite actions

on:
  workflow_dispatch:

jobs:
  try:
    runs-on: ubuntu-latest
    name: try
    steps:
      - name: Inititla setup
        uses: ./.github/workflows/initial-setup
      - name: Try
        run: yarn try
    
