name: Composite actions

on:
  workflow_dispatch:

jobs:
  try:
    runs-on: ubuntu-latest
    name: try
    steps:
      - name: Initial setup
        uses: b12k/gh-actions-node-cache/action.yaml@master
      - name: Try
        run: yarn try
    
