name: Composite actions

on:
  workflow_dispatch:

jobs:
  try:
    runs-on: ubuntu-latest
    name: try
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initial setup
        uses: /.github/action
      - name: Try
        run: yarn try
    
