name: Node Cache

on:
  workflow_dispatch

jobs:
  test-default-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 18
      - name: Install Dependencies
        run: yarn
